cj_website=https://www.cinemajuggs.com/forum/index.php
cj_username=crazen
cj_password=2rowan
cj_titlepage=CinemaJuggs - The Place For Big Boob Lovers - Powered by vBulletin
cj_listoftabs=AI Downloads|JAV Downloads|Webcam-Clips - Downloads|OnlyFans Clips|Movie / Clip - Downloads|Movie / Clip - Streams, Blogs etc|CinemaJuggs Torrents

cd_website=https://cinemageddon.net/
cd_username=crazen
cd_password=eKw92Eez8B
cd_titlepage=cinemageddon
cd_listoftabs=browse.php

db_url=jdbc:mysql://localhost:3306/cinemaj
db_user=admin
db_password=2SecondPC!23
cinemaj=cinemaj
db_nn=nudenet

db_url_cd=jdbc:mysql://localhost:3306/cinemaj
db_user_cd=admin
db_password_cd=2SecondPC!23
cinemageddon=cinemageddon

screenshot_dir=C:\\Users\\Jimmy\\Documents\\GitHub\\Autoclicker






